// Generated by scripts/generate-contracts.mjs. Do not edit.
export const restApiVersion = '1.0.0' as const;
export const websocketProtocolVersion = '1' as const;
export const aiMobileContractVersion = 1 as const;
export const aiMobileCompatibility = {
  minReadableSchemaVersion: 1,
  maxReadableSchemaVersion: 1,
  unknownFutureVersionBehavior: 'safe_error_or_read_only'
} as const;
export const aiMobileJobTypes = [
  'daily_analysis',
  'weekly_analysis',
  'monthly_analysis',
  'quarterly_analysis',
  'yearly_analysis',
  'embedding_index_source',
  'embedding_delete_source',
  'embedding_rebuild_namespace',
  'embedding_verify_namespace',
  'fact_extract_source',
  'fact_reconcile_subject',
  'fact_mark_stale',
  'fact_rebuild_range',
  'graph_update_from_fact',
  'graph_resolve_entity',
  'graph_rebuild_subject',
  'graph_remove_unsupported_edges',
  'retrieval_qa',
  'playground_chat',
  'playground_rebuild'
] as const;
export type AIMobileJobType = (typeof aiMobileJobTypes)[number];
export const aiMobileJobStatuses = [
  'queued',
  'leased',
  'retry_wait',
  'succeeded',
  'failed',
  'cancelled',
  'dead_lettered'
] as const;
export type AIMobileJobStatus = (typeof aiMobileJobStatuses)[number];
export const aiMobileNormalizedErrors = [
  'AUTHENTICATION',
  'PERMISSION',
  'INVALID_CONFIGURATION',
  'UNSUPPORTED_CAPABILITY',
  'UNSUPPORTED_JOB_TYPE',
  'MODEL_UNAVAILABLE',
  'VALIDATION',
  'RATE_LIMIT',
  'QUOTA_EXCEEDED',
  'BUDGET_EXCEEDED',
  'TIMEOUT',
  'CANCELLATION',
  'NETWORK_UNAVAILABLE',
  'PROVIDER_UNAVAILABLE',
  'SAFETY_REFUSAL',
  'CONTEXT_TOO_LARGE',
  'MALFORMED_RESPONSE',
  'UNKNOWN',
  'UNSUPPORTED_AI_SCHEMA_VERSION',
  'READ_ONLY_UNSUPPORTED_AI_SCHEMA'
] as const;
export type AIMobileNormalizedError = (typeof aiMobileNormalizedErrors)[number];
export const aiMobilePrivacyModes = ['DISABLED', 'LOCAL', 'CLOUD', 'HYBRID'] as const;
export type AIMobilePrivacyMode = (typeof aiMobilePrivacyModes)[number];
export const aiMobileProvenanceKinds = [
  'source_revision',
  'analysis_result',
  'vector_chunk',
  'fact',
  'graph_relation',
  'retrieval_plan',
  'provider_attempt'
] as const;
export type AIMobileProvenanceKind = (typeof aiMobileProvenanceKinds)[number];
export const aiMobileExecutionOwnership = {
  daily_analysis: 'desktop_owned_execution',
  weekly_analysis: 'desktop_owned_execution',
  monthly_analysis: 'desktop_owned_execution',
  quarterly_analysis: 'desktop_owned_execution',
  yearly_analysis: 'desktop_owned_execution',
  embedding_index_source: 'desktop_owned_execution',
  embedding_delete_source: 'desktop_owned_execution',
  embedding_rebuild_namespace: 'desktop_owned_execution',
  embedding_verify_namespace: 'desktop_owned_execution',
  fact_extract_source: 'desktop_owned_execution',
  fact_reconcile_subject: 'desktop_owned_execution',
  fact_mark_stale: 'desktop_owned_execution',
  fact_rebuild_range: 'desktop_owned_execution',
  graph_update_from_fact: 'desktop_owned_execution',
  graph_resolve_entity: 'desktop_owned_execution',
  graph_rebuild_subject: 'desktop_owned_execution',
  graph_remove_unsupported_edges: 'desktop_owned_execution',
  retrieval_qa: 'desktop_owned_execution',
  playground_chat: 'desktop_only',
  playground_rebuild: 'desktop_only'
} as const;
export type AIMobileExecutionOwner = (typeof aiMobileExecutionOwnership)[AIMobileJobType];
export const aiMobileMicroUnitPattern = '^[0-9]+$' as const;
export const aiMobileRedactionForbiddenFields = [
  'credential',
  'apiKey',
  'authorization',
  'rawPrompt',
  'rawProviderResponse',
  'leaseToken',
  'reservationOwnerToken'
] as const;
export function isReadableAIMobileSchemaVersion(version: number): boolean {
  return (
    Number.isInteger(version) &&
    version >= aiMobileCompatibility.minReadableSchemaVersion &&
    version <= aiMobileCompatibility.maxReadableSchemaVersion
  );
}
export function aiMobileCompatibilityError(version: number): AIMobileNormalizedError | null {
  if (isReadableAIMobileSchemaVersion(version)) return null;
  return version > aiMobileCompatibility.maxReadableSchemaVersion
    ? 'READ_ONLY_UNSUPPORTED_AI_SCHEMA'
    : 'UNSUPPORTED_AI_SCHEMA_VERSION';
}
export interface AIMobileSyncEnvelope {
  readonly schemaVersion: number;
  readonly ownerId: string;
  readonly workspaceId: string;
  readonly origin: 'desktop' | 'android' | 'backend';
  readonly jobType: AIMobileJobType;
  readonly status: AIMobileJobStatus;
  readonly costMicros: string;
  readonly provenance: ReadonlyArray<{
    readonly kind: AIMobileProvenanceKind;
    readonly id: string;
    readonly revision?: string;
  }>;
}
export const restOperationIds = [
  'bootstrapOwnerDevice',
  'requestDevicePairing',
  'listPairingRequests',
  'createPairingCode',
  'claimPairingCode',
  'approvePairing',
  'consumePairing',
  'listDevices',
  'revokeDevice',
  'listFocusModes',
  'createFocusMode',
  'updateFocusMode',
  'deleteFocusMode',
  'listFocusSessions',
  'createFocusSession',
  'updateFocusSession',
  'listReminders',
  'transitionReminder',
  'listCheckIns',
  'createCheckIn',
  'deleteCheckIn',
  'searchCheckIns',
  'pushSyncOperations',
  'pullSyncOperations',
  'acknowledgeSyncCursor',
  'dailyReport',
  'yearlyHeatmap',
  'registerBackup',
  'listBackups',
  'permanentlyDeleteOwnerData'
] as const;
export type RestOperationId = (typeof restOperationIds)[number];
export type ClientWebSocketMessageType =
  | 'presence.hello'
  | 'presence.heartbeat'
  | 'sync.subscribe'
  | 'reminder.claim-request'
  | 'reminder.claim-release';
export type ServerWebSocketMessageType =
  | 'connection.ready'
  | 'presence.snapshot'
  | 'presence.changed'
  | 'presence.heartbeat-ack'
  | 'sync.subscribed'
  | 'sync.available'
  | 'reminder.claim-granted'
  | 'reminder.claim-denied'
  | 'reminder.claim-released'
  | 'device.revoked'
  | 'error';
export interface WebSocketClientFrame<
  T extends ClientWebSocketMessageType = ClientWebSocketMessageType
> {
  readonly version: typeof websocketProtocolVersion;
  readonly type: T;
  readonly requestId: string;
  readonly sentAt: string;
  readonly payload: Readonly<Record<string, unknown>>;
}
export interface WebSocketServerFrame<
  T extends ServerWebSocketMessageType = ServerWebSocketMessageType
> {
  readonly version: typeof websocketProtocolVersion;
  readonly type: T;
  readonly eventId: string;
  readonly requestId?: string;
  readonly sentAt: string;
  readonly payload: Readonly<Record<string, unknown>>;
}
