// Generated by scripts/generate-contracts.mjs. Do not edit.
export const restApiVersion = '1.0.0' as const;
export const websocketProtocolVersion = '1' as const;
export const restOperationIds = [
  'bootstrapOwnerDevice',
  'requestDevicePairing',
  'listPairingRequests',
  'createPairingCode',
  'claimPairingCode',
  'approvePairing',
  'consumePairing',
  'listDevices',
  'revokeDevice',
  'listFocusModes',
  'createFocusMode',
  'updateFocusMode',
  'deleteFocusMode',
  'listFocusSessions',
  'createFocusSession',
  'updateFocusSession',
  'listReminders',
  'transitionReminder',
  'listCheckIns',
  'createCheckIn',
  'deleteCheckIn',
  'searchCheckIns',
  'pushSyncOperations',
  'pullSyncOperations',
  'acknowledgeSyncCursor',
  'dailyReport',
  'yearlyHeatmap',
  'registerBackup',
  'listBackups',
  'permanentlyDeleteOwnerData'
] as const;
export type RestOperationId = (typeof restOperationIds)[number];
export type ClientWebSocketMessageType =
  | 'presence.hello'
  | 'presence.heartbeat'
  | 'sync.subscribe'
  | 'reminder.claim-request'
  | 'reminder.claim-release';
export type ServerWebSocketMessageType =
  | 'connection.ready'
  | 'presence.snapshot'
  | 'presence.changed'
  | 'presence.heartbeat-ack'
  | 'sync.subscribed'
  | 'sync.available'
  | 'reminder.claim-granted'
  | 'reminder.claim-denied'
  | 'reminder.claim-released'
  | 'device.revoked'
  | 'error';
export interface WebSocketClientFrame<
  T extends ClientWebSocketMessageType = ClientWebSocketMessageType
> {
  readonly version: typeof websocketProtocolVersion;
  readonly type: T;
  readonly requestId: string;
  readonly sentAt: string;
  readonly payload: Readonly<Record<string, unknown>>;
}
export interface WebSocketServerFrame<
  T extends ServerWebSocketMessageType = ServerWebSocketMessageType
> {
  readonly version: typeof websocketProtocolVersion;
  readonly type: T;
  readonly eventId: string;
  readonly requestId?: string;
  readonly sentAt: string;
  readonly payload: Readonly<Record<string, unknown>>;
}
