name: focuslog_mobile
description: FocusLog Flutter foundation.
publish_to: none
version: 0.1.2+3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  connectivity_plus: ^6.1.4
  crypto: ^3.0.6
  cryptography: ^2.7.0
  drift: ^2.28.0
  dynamic_color: ^1.7.0
  file_picker: ^8.3.7
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.3.0
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlcipher_flutter_libs: ^0.6.8
  sqlite3: ^2.7.5
  timezone: ^0.10.1
  uuid: ^4.5.1
  web_socket_channel: ^3.0.3
  workmanager: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.15
  drift_dev: ^2.28.0

flutter:
  uses-material-design: true
